idf_component_register(
    SRCS
        "app_state.c"
        "ble_console.c"
        "can_bus.c"
        "control.c"
        "diagnostics.c"
        "meb-preheat.c"
        "ota_update.c"
        "power_management.c"
        "serial_console.c"
        "settings.c"
        "status_led.c"
    INCLUDE_DIRS "."
    REQUIRES
        esp_driver_twai
        esp_driver_uart
        esp_driver_gpio
        app_update
        esp_pm
        esp_system
        esp_timer
        heap
        bt
        nvs_flash
        espressif__led_strip
)
